### ISSUE TITLE
Cannot auto assign hosts to cluster due to wrong label

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-satellite#57]
I'm provisioning a cluster on Satellite in Azure using these scripts:
https://github.com/lionelmace/satellite-utils/tree/main/terraform/satellite-azure

The creation of the Azure VMs, Satellite location and the cluster is successfull.

I'm missing the final step where the VMs gets automatically assigned to the cluster.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/12241613/166433142-1fee143e-054e-49fa-94d1-976e21de9eba.png">

Where in the terraform script can I change the 

The module `ibm_satellite_location` create a label with zone `eastus-1` instead of `us-east-1`
```
data "ibm_satellite_location" "location" {
        {
            cluster_name = "infrastructure"
            host_id      = "54b69e06af9f051ba8ce"
            host_labels  = {
                "cpu"      = "4"
                "env"      = "prod"
                "memory"   = "16266544"
                "os"       = "RHEL7"
                "provider" = "azure"
                "zone"     = "eastus-1"
            }
            host_name    = "satellite-azure-vm-0"
            ip_address   = "10.0.1.5"
            status       = "normal"
            zone         = "us-east-1"
        },
```
Due to this difference, the host auto assignement cannot performed. Can we fix that in the module to use the format `us-east`?

What is the workaround in the meantime?

**Comment by lionelmace** [comment]
@jsloyer any idea?

**Comment by jsloyer** [comment]
thats actually correct. azure names their zones a little different.  The correct azure zone naming is `eastus-1`.

**Comment by finken2** [comment]
@lionelmace Can you clarify a few things for me?
1) did the control plane hosts assign sucessfully? (i'm guessing yes since you're creating a cluster)
2) when you create the cluster, what zones are you passing in? is that in code, or just locally when you're running? if 1 is yes, and you pass in eastus-1, eastus-2, eastus-3, everything should be good.

**Comment by lionelmace** [comment]
@finken2 
1. Yes
2. Change the location zones solved it. I thought I tried! Thanks
```
  default     = ["eastus-1", "eastus-2", "eastus-3"]
  # default     = ["us-east-1", "us-east-2", "us-east-3"]
```

**Comment by lionelmace** [comment]
@finken2 I created a pull request to enhance the Azure sample with the ability to create a cluster and assign worker nodes.

https://github.com/terraform-ibm-modules/terraform-ibm-satellite/pull/61
